language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly
before_script:
  - composer selfupdate
  - composer install --dev --prefer-dist

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

